[package]
name = "config"
version = "1.0.0"
edition = "2021"
license.workspace = true

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
dotenv = "0.15"
log = { path = "../log" }
ml-utils = { path = "../ml-utils" }